### PR TITLE
#704 add U17 manhole

### PR DESCRIPTION
**Pull request by BigAl737**

### CODE REVIEW

**Comment by BigAl737** [comment]
Can someone please remind me how to update the version number on the website? Thanks.

image

**Comment by derimmer** [comment]
You need to do it in 3 places:

1 in the boardmetadata.xml in the bdXX file. 

2. In the v5boardmetadata.txt and v5boardmetadata.xml files in the boards directory of the VASL module. I may not the exact names of these files but it is something like them. 

3.  In the versions.json file in the boards directory of the website repo on github. 

All of these files can be opened and changed by a simple text editor. 

Strictly speaking the answer to your question is number 3 but if only do that part auto sync won’t work.

**Comment by BigAl737** [comment]
Thanks Doug. For what its worth, I originally did 1 and 3. This didn't change the version number on the website. I just did both files in 2.

The v5boardVersions.txt file didn't even have RBv3 listed. I added it though I don't think updating this file did anything as v0.04 was listed on the website without RBv3 included within this file.

Updating the v5boardVersions.xml file was the magic ticket I think as the website showed v0.05 soon after I pushed the change to this file.

Thanks for your help.

**Comment by bkemp01** [comment]
I also believe there is a minor delay before the site reflects changes pushed up to Github, maybe 15 minutes or so.

**Comment by BigAl737** [comment]
Thanks Brian. I remember that in the past. Thus I was somewhat surprised today when the change was reflected within minutes.

**Comment by derimmer** [comment]
Brian you are right. 

Al, steps 1 and 2 are what is required for auto syncing. IMHO, This is more useful than posting to the website. But both are good.

**Comment by BigAl737** [comment]
Good to know Doug. Thanks.

To clarify a little more FYI...

I did steps 1 and 3 last night. Checked the version status this morning. No change.

Did step 2 this morning as I outlined above. Version change observed within minutes. Also auto syncing tested and confirmed.

I need to add this conversation to a help file. I'll bet I don't remember it next time I post a board update :-)

**Pull request merged**
