### PR TITLE
Adding several enhanced scenario setups compatible with VASL 6.6.1.

### PR DESCRIPTION
**Pull request by brookscl**
I've been building enhanced scenarios for a variety of west coast USA tournaments and thought it might be helpful to share with the larger community. These were all saved with VASL 6.6.1.

### CODE REVIEW

**Comment by derimmer** [comment]
I would suggest amending the name of the files to reflect the VASL version that they were built for. Just a thought. If you want to merge the PR, go ahead. If github won't let you merge (a permissions thing), let me know and we can fix that.

**Comment by brookscl** [comment]
Is this naming convention OK?

`ASL-180 The T-Patchers Enhanced for 6.6.vsav`

If figure major.minor might be descriptive enough. Let me know if you have an alternate suggestion. I'll update this PR with the changes.

I don't have PR merge rights and am happy to do so if you decide to grant.

**Comment by derimmer** [comment]
Naming convention looks good to me. 

 

The whole vasl site is open to anyone and am happy to grant permission.

**Comment by derimmer** [comment]
@brookscl for some reason this commit does not seem to have worked. When I look at the repository I do not see the commit or the changes list. On this page it appears to have worked. I am not at all sure what happend. What I would suggest is that you (a) create a new branch (b) push your commit to that branch and (c) merge the branch into gh-pages. 

In addition, you also need to change the scen.html file in the include directory to add each of your new setups. I have added the first one as example. But it will have no effect until the new file gets into the setups directory.

**Comment by brookscl** [comment]
So odd. And I swear after merging it I inspected the repo and saw my changes there. This should be an easy redo.

I thought the scen.html file was autogenerated - my bad. I'll get that done as well with this new (hopefully sticky) change.

**Comment by brookscl** [comment]
I think the setups are good now. Question: are we manually maintaining the `scan.html` include, or generating it with Jekyll?

**Comment by styson** [comment]
It should get generated with Jekyll, but it goes to a manual process then so be it.

**Comment by brookscl** [comment]
I'm able to gen it locally so I'll go from there. Expect another commit shortly with that.

**Comment by brookscl** [comment]
@styson sent you an email. I think I figured out why Jekyll wasn't giving reliable results for me locally, and I have a patch coming shortly that should make the build script more reliable. Looks like we also manually delete all the stuff from `<h1>old</h1>` to the bottom.

**Pull request merged**
